theme: jekyll-theme-minimal
title: JASA ACS Reproducibility Guide
description: Reproducibility guide for authors and reviewers publishing in the Journal of the American Statistical Association (JASA) Applications and Case Studies (ACS) section. 
logo: assets/asa_logo.jpg
show_downloads: false
